export const computerEngineeringSubjects: Record<string, string[]> = {
    "first-semester": [
        "Applied Mechanics [CE 401]",
        "Basic Electrical Engineering [EE 401]",
        "Engineering Physics [SH 402]",
        "Engineering Drawing I [ME 401]",
        "Engineering Mathematics I [SH 401]",
        "Computer Programming [CT 401]",
    ],
    "second-semester": [
        "Engineering Mathematics II [SH 451]",
        "Engineering Drawing II [ME 451]",
        "Basic Electronics Engineering [EX 451]",
        "Engineering Chemistry [SH 453]",
        "Fundamental of Thermodynamics & Heat Transfer [ME 452]",
        "Workshop Technology [ME 453]",
    ],
    "third-semester": [
        "Engineering Mathematics III [SH 501]",
        "Object Oriented Programming [CT 501]",
        "Electric Circuit Theory [EE 501]",
        "Theory of Computation [CT 502]",
        "Electronics Devices and Circuit [EX 501]",
        "Digital Logic [EX 502]",
        "Electromagnetics [EX 503]",
    ],
    "fourth-semester": [
        "Numerical Method [SH 553]",
        "Applied Mathematics [SH 551]",
        "Instrumentation I [EE 552]",
        "Data Structure and Algorithm [CT 552]",
        "Microprocessor [EX 551]",
        "Discrete Structure [CT 551]",
        "Electrical Machine [EE 554]",
    ],
    "fifth-semester": [
        "Communication English [SH 601]",
        "Probability and Statistics [SH 602]",
        "Computer organization and Architecture [CT 603]",
        "Software Engineering [CT 601]",
        "Computer Graphics [EX 603]",
        "Instrumentation II [EX 602]",
        "Data Communication [CT 602]",
    ],
    "sixth-semester": [
        "Engineering Economics [CE 655]",
        "Object Oriented Analysis and Design [CT 651]",
        "Artificial Intelligence [CT 653]",
        "Operating System [CT 656]",
        "Embedded System [CT 655]",
        "Database Management System [CT 652]",
        "Minor Project [CT 654]",
    ],
    "seventh-semester": [
        "ICT Project Management [CT 701]",
        "Organization and Management [ME 708]",
        "Energy Environment and Society [EX 701]",
        "Distributed System [CT 703]",
        "Computer Networks and Security [CT 702]",
        "Digital Signal Analysis and Processing [CT 704]",
        "Project (Part A) [CT 707]",
        "Elective I : Advanced Java [CT 725 01]",
        "Elective I : Aeronautical Telecom [EX 725 04]",
        "Elective I : Biomedical Instrumentation",
        "Elective I : Data Mining",
        "Elective I : Embedded System",
        "Elective I : Image Processing [CT 725 04]",
        "Elective I : Microwave Engineering [EX 725 05]",
        "Elective I : Operating System",
        "Elective I : Radar Technology",
        "Elective I : Satellite Communicaation",
        "Elective I : Web Technology [CT 725 05]",
    ],
    "seventh-semester-electives": [
        "Elective I : Advanced Java [CT 725 01]",
        "Elective I : Aeronautical Telecom [EX 725 04]",
        "Elective I : Biomedical Instrumentation",
        "Elective I : Data Mining",
        "Elective I : Embedded System",
        "Elective I : Image Processing [CT 725 04]",
        "Elective I : Microwave Engineering [EX 725 05]",
        "Elective I : Operating System",
        "Elective I : Radar Technology",
        "Elective I : Satellite Communicaation",
        "Elective I : Web Technology [CT 725 05]",
    ],
    "eighth-semester": [
        "Engineering Professional Practice [CE 752]",
        "Information Systems [CT 751]",
        "Internet and Intranet [CT 754]",
        "Project (Part B) [CT 755]",
        "Simulation and Modelling [CT 753]",
        "Elective II : ADVANCED COMPUTER ARCHITECTURE [CT 765 04]",
        "Elective II : AGILE SOFTWARE DEVELOPMENT [CT 765 02]",
        "Elective II : BIG DATA TECHNOLOGIES [CT 765 07]",
        "Elective II : BROADCAST ENGINEERING [EX 765 03]",
        "Elective II : DATABASE MANAGEMENT SYSTEMS [EX 765 06]",
        "Elective II : NETWORKING WITH IPV6 [CT 765 03]",
        "Elective II : OPTICAL FIBER COMMUNICATION SYSTEM [EX 765 01]",
        "Elective II : WIRELESS COMMUNICATIONS [EX 765 04]",
        "Elective III : ARTIFICIAL INTELLIGENCE [CT 785 06]",
        "Elective III : ENTERPRISE APPLICATION DESIGN AND DEVELOPMENT [CT 785 04]",
        "Elective III : GEOGRAPHICAL INFORMATION SYSTEM [CT 785 07]",
        "Elective III : MULTIMEDIA SYSTEM [CT 785 03]",
        "Elective III : POWER ELECTRONICS [EE 785 07]",
        "Elective III : REMOTE SENSING [CT 785 01]",
        "Elective III : SPEECH PROCESSING [CT 785 08]",
        "Elective III : TELECOMMUNICATION [EX 785 03]",
        "Elective III : XML: FOUNDATIONS, TECHNIQUES AND APPLICATIONS [CT 785 05]",
    ],
};
